--- #YAML:1.0
name:               Apache2-FileHash
version:            0.01
abstract:           Methods to store and retrieve files using a hashing methodology.
author:
    - A. U. Thor <bpm@localdomain>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
